### ISSUE TITLE
Disable "text message" notification radio control and add explanatory text

### ISSUE THREAD

**Issue by thammerl** [mcallistersean/b2-issue-tracker#19]
Since we are not capable yet of sending notifications, we should disable the option for notification rules and add a message explaining that this will be possible in the future.

**Comment by mcallistersean** [comment]
Notifications are possible, but need some more work to get them fully working.

Current status:

- Geographic notifications (point + radius), filtered by organisation and issue type work with sms and email.
- Mention notifications work with email only and are not yet configurable

Email notifications on development is done by printing the mail to the terminal window where the dev server is running.

**Comment by thammerl** [comment]
So for some notifications we support text messages and for some we don't? Should we disable the text message options for those notifications that don't and add an explanatory text that says that this will be possible once an SMS gateway is configured? We just wanted to make sure that as much as possible within the application is self-explanatory without the need of a handbook before they start testing.

**Comment by mcallistersean** [comment]
> So for some notifications we support text messages and for some we don't?

Yes, the 2 notification systems (one for issue creation and geograpic range, the other for user/org mentions in comments) are implemented differently at the moment. I'll try to work on it during the weekend and hope to get a proper implementation by Monday that works for both cases.
I have implemented the corresponding settings in 8bbb7714d62f12a57b11a16b955a03bbcf9b603c

**Comment by mcallistersean** [comment]
I have implemented a very straightforward approach to this issue in 6cd2d285d643e32ed462737f4fd595b1c153161e

This will suffice for now, but I am thinking about refactoring the whole notification approach to accomodate  multiple backends, including web/mobile notifications with acknowledgement support.
Currently all notifications are sent immediately. We will need some kind of throttling in the future.
