### ISSUE TITLE
Safari 8 support

### ISSUE THREAD

**Issue by mcallistersean** [mcallistersean/b2-issue-tracker#29]
Our layout breaks on Safari 8.
@thammerl Is flexbox the only problem with Safari 8? Or did you notice further problems.
Any reason Isabella can not update? There is no version of OSX that I know of where Safari 8 is the latest available version.
We are using autoprefixer and I have added more configuration for it in 0dd072e.
But I don't think this is actually going to work, because the css looks rather similar to before.

**Comment by mcallistersean** [comment]
Oh, and Safari 8 should actually support flexbox, with prefixes. 
Go here http://caniuse.com/#search=flexbox and click on 'Show all'

**Comment by thammerl** [comment]
I just noticed issues related to flexbox.

I see prefixed CSS rules with `-webkit` prefix locally. Can you deploy a new version to https://b2it.brickwall.at/ so Isabella can test it?

**Comment by mcallistersean** [comment]
Damn you javascript build tools!

**Comment by mcallistersean** [comment]
On a more serious note, you are right, something seems to remove all the nice prefixes again.
I can't get a production build that has the -webkit prefixes.
Have to read some docs ..

**Comment by mcallistersean** [comment]
Ok, webkit prefixes are in ded7c87
@thammerl can you ask isabella to check again?

**Comment by thammerl** [comment]
Nice!

She wasn't at the office anymore but I've sent her an e-mail as you've probably already noticed. ;)

**Comment by mcallistersean** [comment]
I'll close this and hope that everybody has updated their browsers by now. If it is still a problem please reopen.
