### ISSUE TITLE
Mentioning triggers scoll to top

### ISSUE THREAD

**Issue by thammerl** [mcallistersean/b2-issue-tracker#30]
When there are enough comments so that the div-scrollbar is displayed, the div scrolls to the top when the users enters an `@` sign.

For example, currently reproducable with https://b2it.brickwall.at/issue/11.

**Comment by thammerl** [comment]
Maybe somehow related to [common pitfalls of draft-js](https://facebook.github.io/draft-js/docs/advanced-topics-issues-and-pitfalls.html#common-pitfalls)? Is the draft.css included in the page?

**Comment by thammerl** [comment]
This problem could be solved by setting `overflow: hidden` on the body tag. Maybe this is something draft.css would do.

**Comment by mcallistersean** [comment]
This has been bugging me for some time. There is a difference in the behaviour depending wheter I have the dev tools (docked) open or not. 
https://github.com/facebook/draft-js/issues/14

**Comment by mcallistersean** [comment]
And it seems to work in firefox

**Comment by thammerl** [comment]
Is it possible to add a CSS class only for the body of the frontpage? `overflow: hidden` fixes the problem for me also in Chrome.

**Comment by thammerl** [comment]
I don't think it's related to the issue you referenced. The mention plugin just doesn't seem to work well inside a scrollable div. It seems to insert the flyout outside of the scrollable div making the body scrollable which in turn triggers the scrolling to the top. With `overflow: hidden` the body never gets a scrollbar and therefor never triggers the scrolling.

**Comment by mcallistersean** [comment]
Ok, I commited the "overflow: hidden" hack, this should fix it for now, but I am sure the problem will resurface at some point.
Perhaps this is related and will be fixed in the next draft js version: https://github.com/draft-js-plugins/draft-js-plugins/pull/309

**Comment by thammerl** [comment]
Thx! It's not *that* much of hack. ;) The way the page is designed, the body really never should be scrollable.

Yes, this looks related.

**Comment by Some1Else** [comment]
Wait, guys! Do all pages that use draft.js now have to have `overflow: hidden;` set on the `<body>` tag?
