### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by IsabellaReinhard** [mcallistersean/b2-issue-tracker#37]
Make invitation based

**Comment by mcallistersean** [comment]
The solution that I am working on will implement this functionality:

- superusers are able to create organisations and invite the initial users (via email) and select roles for each of them
- the users will sign up using the link provided in the email, these users will receive the role the administrator has selected in the first step
- Administrators (or owners?) are allowed to invite more people to their organisation

**Comment by IsabellaReinhard** [comment]
Super!

**Comment by mcallistersean** [comment]
Done. The latest version is now also deployed.

**Comment by IsabellaReinhard** [comment]
Hi Sean,

Super, danke! Ist es am gleichen link wie immer deployed?

Liebe Grüße,

Isabella

On Mon, Oct 10, 2016 at 12:02 AM, Sean Mc Allister <notifications@github.com

**Comment by mcallistersean** [comment]
yep, https://b2it.brickwall.at/
