### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by mcallistersean** [mcallistersean/b2-issue-tracker#43]
Marketing text etc.

**Comment by IsabellaReinhard** [comment]
Text for landing page:

Toucan is an online emergency relief platform. It enables communication among humanitarian actors in emergency situations. Toucan facilitates sharing information and coordinating resources, whether supplying food or urgent medical assistance. Organisations become more aware of who provides what services where.

Toucan was developed by BeeTwo. (bitte zu www.beetwo.at verlinken)

Danke!

**Comment by mcallistersean** [comment]
This is done. The text can be seen here: https://b2it.brickwall.at/
